server:
  port: 8762
spring:
  application:
    name: eureka2
  boot:
    admin:
      client:
        url: http://localhost:9083
management:
  endpoints:
    web:
      exposure:
        include: '*'


# Eureka Server

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true #false????????????????????????????true??????false???????????????
    fetch-registry: true #???????????????????????false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/  # ??????
