server:
  port: 7963 # ??

spring:
  application:
    name: config-server # ???
  boot:
    admin:
      client:
        url: http://localhost:9083
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/goldhadis/SpringCloudStudy.git
          search-paths: springcloud-config-server/config-repo
          username: goldhadis
          password: ILovELoL520
management:
  endpoints:
    web:
      exposure:
        include: '*'

#
service:
  name:
    xxx-oauth-server: http://xxx-config-order/

# ?? Eureka Server ????
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/


logging:
  pattern:
    console: '%d{HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'

