server:
  port: 8761
spring:
  application:
    name: eureka1
  boot:
    admin:
      client:
        url: http://localhost:9083



# Eureka Server

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  client:
    register-with-eureka: true #false????????????????????????????true??????false???????????????
    fetch-registry: true #???????????????????????false
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/  # ??????

#开放端点用于SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: '*'