server:
  port: 8762
spring:
  application:
    name: eureka2


# Eureka Server

eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    register-with-eureka: true #false????????????????????????????true??????false???????????????
    fetch-registry: true #???????????????????????false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/  # ??????
