server:
  port: 8763
spring:
  application:
    name: eureka3
  boot:
    admin:
      client:
        url: http://localhost:9083
management:
  endpoints:
    web:
      exposure:
        include: '*'


# Eureka Server

eureka:
  instance:
    hostname: eureka3
    prefer-ip-address: true
  client:
    register-with-eureka: true #false????????????????????????????true??????false???????????????
    fetch-registry: true #???????????????????????false
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  # ??????
